'use client';

import React, { useState, useEffect } from 'react';
import { EquipmentList } from './equipment-list';
import { EquipmentDetailModal } from './equipment-detail-modal';
import { EquipmentSearchFilters } from './equipment-search-filters';
import { EquipmentAlertsPanel } from './equipment-alerts-panel';
import { Plus } from 'lucide-react';

export interface Equipment {
  id: string;
    inventoryNumber: string;
      service: string;
        unit: string;
          location: string;
            equipmentName: string;
              brand: string;
                model: string;
                  equipmentSerialNumber: string;
                    tubeSerialNumber: string;
                      resolutionNumber: string;
                        resolutionDate: string;
                          authorizationStatus: 'vigente' | 'vencida' | 'en_tramite' | 'suspendida';
                            observations: string;
                              status: 'operativo' | 'fuera_de_servicio' | 'prestamo' | 'baja';
                                createdAt: string;
                                  updatedAt: string;
                                    lastModifiedBy: string;
                                      documents: EquipmentDocument[];
                                        history: EquipmentHistoryEntry[];
                                          alerts: Alert[];
                                          }

                                          export interface EquipmentDocument {
                                            id: string;
                                              name: string;
                                                type: 'resolucion' | 'oficio' | 'acta_instalacion' | 'certificados' | 'manuales' | 'baja' | 'cambio_tubo' | 'prestamo' | 'otros';
                                                  fileUrl: string;
                                                    fileName: string;
                                                      uploadedAt: string;
                                                        uploadedBy: string;
                                                          size: number;
                                                          }

                                                          export interface EquipmentHistoryEntry {
                                                            id: string;
                                                              action: string;
                                                                description: string;
                                                                  timestamp: string;
                                                                    user: string;
                                                                      details?: Record<string, any>;
                                                                      }

                                                                      export interface Alert {
                                                                        id: string;
                                                                          type: 'cambio_tubo' | 'cambio_arquitectura' | 'baja' | 'prestamo' | 'vencimiento' | 'en_tramite' | 'documentacion_pendiente';
                                                                            message: string;
                                                                              severity: 'info' | 'warning' | 'error';
                                                                                createdAt: string;
                                                                                  read: boolean;
                                                                                  }

                                                                                  const INITIAL_EQUIPMENT: Equipment[] = [
                                                                                    {
                                                                                        id: '1',
                                                                                            inventoryNumber: '2-011796',
                                                                                                service: 'Dental',
                                                                                                    unit: 'Sala Dental',
                                                                                                        location: 'Dental',
                                                                                                            equipmentName: 'Equipo de Rayos X Dental',
                                                                                                                brand: 'Focus',
                                                                                                                    model: 'Focus Intra oral',
                                                                                                                        equipmentSerialNumber: 'F22489',
                                                                                                                            tubeSerialNumber: '15209',
                                                                                                                                resolutionNumber: 'A2004760',
                                                                                                                                    resolutionDate: '2024-01-23',
                                                                                                                                        authorizationStatus: 'vigente',
                                                                                                                                            observations: '',
                                                                                                                                                status: 'operativo',
                                                                                                                                                    createdAt: '2024-01-23',
                                                                                                                                                        updatedAt: '2024-01-23',
                                                                                                                                                            lastModifiedBy: 'Sistema',
                                                                                                                                                                documents: [],
                                                                                                                                                                    history: [],
                                                                                                                                                                        alerts: [],
                                                                                                                                                                          },
                                                                                                                                                                            {
                                                                                                                                                                                id: '2',
                                                                                                                                                                                    inventoryNumber: '2-001764',
                                                                                                                                                                                        service: 'Dental',
                                                                                                                                                                                            unit: 'Box 8',
                                                                                                                                                                                                location: 'Rx Dental',
                                                                                                                                                                                                    equipmentName: 'Equipo de Rayos X Dental',
                                                                                                                                                                                                        brand: 'Focus',
                                                                                                                                                                                                            model: 'Focus Intra oral',
                                                                                                                                                                                                                equipmentSerialNumber: 'F22496',
                                                                                                                                                                                                                    tubeSerialNumber: '15104',
                                                                                                                                                                                                                        resolutionNumber: '2305529684',
                                                                                                                                                                                                                            resolutionDate: '2023-12-15',
                                                                                                                                                                                                                                authorizationStatus: 'vigente',
                                                                                                                                                                                                                                    observations: '',
                                                                                                                                                                                                                                        status: 'operativo',
                                                                                                                                                                                                                                            createdAt: '2023-12-15',
                                                                                                                                                                                                                                                updatedAt: '2023-12-15',
                                                                                                                                                                                                                                                    lastModifiedBy: 'Sistema',
                                                                                                                                                                                                                                                        documents: [],
                                                                                                                                                                                                                                                            history: [],
                                                                                                                                                                                                                                                                alerts: [],
                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                  ];
                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                  export function EquipmentApp() {
                                                                                                                                                                                                                                                                    const [equipment, setEquipment] = useState<Equipment[]>(INITIAL_EQUIPMENT);
                                                                                                                                                                                                                                                                      const [selectedEquipment, setSelectedEquipment] = useState<Equipment | null>(null);
                                                                                                                                                                                                                                                                        const [isDetailModalOpen, setIsDetailModalOpen] = useState(false);
                                                                                                                                                                                                                                                                          const [filteredEquipment, setFilteredEquipment] = useState<Equipment[]>(INITIAL_EQUIPMENT);
                                                                                                                                                                                                                                                                            const [activeAlerts, setActiveAlerts] = useState<Alert[]>([]);
                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                              useEffect(() => {
                                                                                                                                                                                                                                                                                  const allAlerts = equipment.flatMap(eq => eq.alerts).filter(a => !a.read);
                                                                                                                                                                                                                                                                                      setActiveAlerts(allAlerts);
                                                                                                                                                                                                                                                                                        }, [equipment]);
                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                          const handleAddEquipment = () => {
                                                                                                                                                                                                                                                                                              setSelectedEquipment(null);
                                                                                                                                                                                                                                                                                                  setIsDetailModalOpen(true);
                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                      const handleSelectEquipment = (eq: Equipment) => {
                                                                                                                                                                                                                                                                                                          setSelectedEquipment(eq);
                                                                                                                                                                                                                                                                                                              setIsDetailModalOpen(true);
                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                  const handleSaveEquipment = (updatedEquipment: Equipment) => {
                                                                                                                                                                                                                                                                                                                      if (selectedEquipment) {
                                                                                                                                                                                                                                                                                                                            setEquipment(equipment.map(eq => eq.id === updatedEquipment.id ? updatedEquipment : eq));
                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                      setEquipment([...equipment, { ...updatedEquipment, id: Date.now().toString() }]);
                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                              setIsDetailModalOpen(false);
                                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                  const handleDeleteEquipment = (id: string) => {
                                                                                                                                                                                                                                                                                                                                                      setEquipment(equipment.filter(eq => eq.id !== id));
                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                          const handleFilterChange = (filtered: Equipment[]) => {
                                                                                                                                                                                                                                                                                                                                                              setFilteredEquipment(filtered);
                                                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                                                                                                                                                      <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100">
                                                                                                                                                                                                                                                                                                                                                                            <div className="max-w-7xl mx-auto p-6 space-y-6">
                                                                                                                                                                                                                                                                                                                                                                                    {/* Header */}
                                                                                                                                                                                                                                                                                                                                                                                            <div className="flex flex-col gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                                                                                  <h1 className="text-4xl font-bold text-slate-900 mb-2">Gestión de Equipos Radiológicos</h1>
                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-slate-600">Sistema integral de gestión de equipos generadores de radiación</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex justify-between items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="text-sm text-slate-600">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Total de equipos: <span className="font-semibold text-slate-900">{equipment.length}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Button onClick={handleAddEquipment} className="gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Plus className="w-4 h-4" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Nuevo Equipo
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Alerts Panel */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {activeAlerts.length > 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <EquipmentAlertsPanel alerts={activeAlerts} equipment={equipment} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* Search and Filters */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <EquipmentSearchFilters
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          equipment={equipment}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onFilterChange={handleFilterChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* List */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <EquipmentList
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      equipment={filteredEquipment}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onSelectEquipment={handleSelectEquipment}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onDeleteEquipment={handleDeleteEquipment}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Detail Modal */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <EquipmentDetailModal
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            equipment={selectedEquipment}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    isOpen={isDetailModalOpen}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onClose={() => setIsDetailModalOpen(false)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onSave={handleSaveEquipment}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
